name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt install
      run:  sudo apt install csh gfortran pgplot5 libhdf4-dev libhdf5-dev libcfitsio-dev libnetcdf-dev -y
    - name: autoconf
      run:  autoconf
    - name: configure
      run: ./configure --with-yapp=pgplot --enable-debug
    - name: build1
      run: make build1 
    - name: build2
      run: make build2
    - name: build3
      run: make build3
    - name: build4
      run: make build4
    - name: make check
      run: make check checklog
    - name: make bench
      run: make bench
    
